/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	aws_project_region: 'ap-south-1',
	aws_cognito_identity_pool_id:
		'ap-south-1:aa128030-887d-4d4d-8bb8-9710a79a1153',
	aws_cognito_region: 'ap-south-1',
	aws_user_pools_id: 'ap-south-1_oqe6vE4oE',
	aws_user_pools_web_client_id: '7o447pchrqnshn6v461ifsmhg0',
	oauth: {},
};

export default awsmobile;
